apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: multi-worker
spec:
  cleanPodPolicy: None
  tfReplicaSpecs:
    Worker:
      replicas: 6
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: tensorflow
              image: kubeflow/tf2-mwms:k8s
              volumeMounts:
              - mountPath: /data
                name: dataset
              - mountPath: /models
                name: models
              - mountPath: /logs
                name: tblogs
              resources:
                request:
                  cpu: 4
                  memory: 10Gi
          volumes:
          - hostPath:
              path: /home/sdev/s3mount/yongxi/training/CVR/
              readOnly: true
            name: dataset
          - hostPath:
              path: /home/sdev/s3mount/yongxi/training/models/cvr
            name: models
          - hostPath:
              path: /home/sdev/s3mount/yongxi/TBlogs/cvr/DeepFM
            name: tblogs
