apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  labels:
    app: training
  name: yongxiy-horovod-cvr-train
spec:
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - args:
            - mpirun --allow-run-as-root -bind-to none -map-by slot -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python model.py
            command:
            - /bin/bash
            - -c
            image: cvrhvd:train
            imagePullPolicy: IfNotPresent
            name: mpi-launcher
            resources:
              request:
                cpu: 1
                memory: 3Gi
    Worker:
      replicas: 5
      template:
        spec:
          containers:
          - image: cvrhvd:train
            imagePullPolicy: IfNotPresent
            name: mpi-worker
            resources:
              request:
                cpu: 4
                memory: 10Gi
            volumeMounts:
            - mountPath: /data
              name: dataset
            - mountPath: /models
              name: models
            - mountPath: /logs
              name: tblogs
          volumes:
          - hostPath:
              path: /home/sdev/s3mount/yongxi/training/CVR/
              readOnly: true
            name: dataset
          - hostPath:
              path: /home/sdev/s3mount/yongxi/training/models/cvr
            name: models
          - hostPath:
              path: /home/sdev/s3mount/yongxi/TBlogs/cvr/DeepFM
            name: tblogs
      restartPolicy: None
  slotsPerWorker: 1
