apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: multi-worker
spec:
  cleanPodPolicy: None
  tfReplicaSpecs:
    Worker:
      replicas: 6
      # restartPolicy: onFailure
      template:
        spec:
          containers:
            - name: tensorflow
              image: kubeflow/multi_worker_strategy:v1.0
              volumeMounts:
                - mountPath: /train
                  name: training
              resources:
                request:
                  cpu: 1
                  memory: 3Gi
          volumes:
            - name: training
              persistentVolumeClaim:
                claimName: strategy-volume
