apiVersion: v1
kind: PersistentVolume
metadata:
  name: strategy-pv
  labels:
    app: strategy-volume
spec:
  storageClassName: s3fs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/sdev/s3mount/yongxi/tf-operator"
