apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: customized-
commonLabels:
  app: fuck-you

# it a relative directory $path from `kustomize build $path`
bases:
- ../../base

patchesJson6902:
- target:
    group: kubeflow.org
    version: v1alpha2
    kind: MPIJob
    name: tensorflow-mnist
    namespace: default
  path: hvd6902.yaml