apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tfserving-pvc
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: s3fs
  selector:
    matchLabels:
      type: s3fs-storage
      app: tfserving