apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorboard-deployment
spec:
  selector:
    matchLabels:
      app: tb-image
  replicas: 2
  template:
    metadata:
      labels:
        app: tb-image
    spec:
      containers:
      - name: tb-image
        image: tensorflow/tensorflow
        command: ["/bin/bash","-c"]
        args:
          - "tensorboard --logdir /tmp/logs --bind_all"
        volumeMounts:
        - mountPath: "/tmp/logs"
          name: tb-logs
        resources:
          limits:
            memory: "4Gi"
            cpu: "4"
        ports:
        - containerPort: 6006
      volumes:
        - name: tb-logs
          persistentVolumeClaim:
            claimName: tensorboard-pvc
      # restartPolicy: OnFailure

